/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JsonRouteImport } from './routes/json'
import { Route as DotwellKnownDiscordRouteImport } from './routes/[.]well-known.discord'
import { Route as ApiPublicAssetJsonRouteImport } from './routes/api/public/asset-json'
import { Route as ApiPublicAssetThumbnailRouteImport } from './routes/api/public/asset-thumbnail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonRoute = JsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownDiscordRoute = DotwellKnownDiscordRouteImport.update({
  id: '/.well-known/discord',
  path: '/.well-known/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssetJsonRoute = ApiPublicAssetJsonRouteImport.update({
  id: '/api/public/asset-json',
  path: '/api/public/asset-json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssetThumbnailRoute = ApiPublicAssetThumbnailRouteImport.update({
  id: '/api/public/asset-thumbnail',
  path: '/api/public/asset-thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/json': typeof JsonRoute
  '/.well-known/discord': typeof DotwellKnownDiscordRoute
  '/api/public/asset-json': typeof ApiPublicAssetJsonRoute
  '/api/public/asset-thumbnail': typeof ApiPublicAssetThumbnailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/json': typeof JsonRoute
  '/.well-known/discord': typeof DotwellKnownDiscordRoute
  '/api/public/asset-json': typeof ApiPublicAssetJsonRoute
  '/api/public/asset-thumbnail': typeof ApiPublicAssetThumbnailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/json': typeof JsonRoute
  '/.well-known/discord': typeof DotwellKnownDiscordRoute
  '/api/public/asset-json': typeof ApiPublicAssetJsonRoute
  '/api/public/asset-thumbnail': typeof ApiPublicAssetThumbnailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/json'
    | '/.well-known/discord'
    | '/api/public/asset-json'
    | '/api/public/asset-thumbnail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/json'
    | '/.well-known/discord'
    | '/api/public/asset-json'
    | '/api/public/asset-thumbnail'
  id:
    | '__root__'
    | '/'
    | '/json'
    | '/.well-known/discord'
    | '/api/public/asset-json'
    | '/api/public/asset-thumbnail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JsonRoute: typeof JsonRoute
  DotwellKnownDiscordRoute: typeof DotwellKnownDiscordRoute
  ApiPublicAssetJsonRoute: typeof ApiPublicAssetJsonRoute
  ApiPublicAssetThumbnailRoute: typeof ApiPublicAssetThumbnailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/discord': {
      id: '/.well-known/discord'
      path: '/.well-known/discord'
      fullPath: '/.well-known/discord'
      preLoaderRoute: typeof DotwellKnownDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asset-json': {
      id: '/api/public/asset-json'
      path: '/api/public/asset-json'
      fullPath: '/api/public/asset-json'
      preLoaderRoute: typeof ApiPublicAssetJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asset-thumbnail': {
      id: '/api/public/asset-thumbnail'
      path: '/api/public/asset-thumbnail'
      fullPath: '/api/public/asset-thumbnail'
      preLoaderRoute: typeof ApiPublicAssetThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JsonRoute: JsonRoute,
  DotwellKnownDiscordRoute: DotwellKnownDiscordRoute,
  ApiPublicAssetJsonRoute: ApiPublicAssetJsonRoute,
  ApiPublicAssetThumbnailRoute: ApiPublicAssetThumbnailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
